### ISSUE TITLE
Add GetNeighbors function

### ISSUE THREAD

**Issue by richardartoul** [mmcloughlin/geohash#1]
Most popular Geohash libraries have a GetNeighbors function (including other Golang libraries). Of all the Golang libraries, this one seems like it was put together with the most thought and has the nicest API. Would you mind if I make a pull request adding this function? Its a super useful utility to have, and figuring out how to do it actually took me a long time and I'd love to save some people the work in the future.

Also thank you for putting this nice library together :)

**Comment by mmcloughlin** [comment]
`GetNeighbors()` is definitely an omission from this library. I would welcome a pull request. Thank you for taking the time to look at this.

**Comment by yl2chen** [comment]
+1

**Comment by richardartoul** [comment]
Sounds good, I'll make the pull request soon. There are a few implementation details that I'm not 100% on, but we can discuss those in the P.R

**Comment by mmcloughlin** [comment]
PR #2 merged. Thank you for your contribution.
