### ISSUE TITLE
Build fail after update

### ISSUE THREAD

**Issue by Glagnar** [mmcloughlin/geohash#12]
I get this error after pulling the following commit : ed078506daaeeca0af46537db6763151a70538d9

```go
2018/06/28 12:44:56 duplicate symbol github.com/ttnsignalmapper/vendor/github.com/mmcloughlin/geohash.EncodeInt (types 1 and 1) in github.com/ttnsignalmapper/vendor/github.com/mmcloughlin/geohash and $WORK/b087/_pkg_.a(asm_x86.o)
```

**Comment by mmcloughlin** [comment]
That looks bad. Would you be able to share some more about your environment (`go version`)? Also, which tool are you using to vendor the package?

**Comment by mmcloughlin** [comment]
How are you getting on with this @Glagnar ? Seems like a nasty bug so I would love to get to the bottom of it. Cheers!

**Comment by mmcloughlin** [comment]
Closing due to lack of information. Happy to investigate if you can give me something to go on.
