### ISSUE TITLE
single neighbor methods

### ISSUE THREAD

**Issue by predmond** [mmcloughlin/geohash#13]
It would be great if there was a `Neighbor` function to return a single neighbor.

Something like:
```
type Heading int
const (
  North Heading = iota
  NorthEast
  East
  SouthEast
  South
  SouthWest
  West
  NorthWest
)

func Neighbor(h Heading) string
```
the constants would be useful for the result of `Neighbors` too.

**Comment by mmcloughlin** [comment]
Thanks for posting the issue, I agree this would be a great feature.

I should be able to get around to this soon, but I'll appy the #hacktoberfest label in case anyone feels like helping out 👻

**Comment by mb-14** [comment]
I would like to work on this

**Comment by mmcloughlin** [comment]
Thanks @mb-14 !
