### ISSUE TITLE
Can you cut a release for this library so users can pin it?

### ISSUE THREAD

**Issue by parkwherever** [mmcloughlin/geohash#15]

**Comment by mmcloughlin** [comment]
Sorry for the delay. Yes of course!

**Comment by mmcloughlin** [comment]
Pushed tag `v0.9.0`. I am almost certain I'm ready to declare `v1.0.0` on this but I just want to think a little first. With 4,581 clones in the last two weeks [Hyrum's Law](http://www.hyrumslaw.com/) pretty much forces no changes anyway :)
