### ISSUE TITLE
Compress area of geohashes - similiar to georaptor

### ISSUE THREAD

**Issue by odannyc** [mmcloughlin/geohash#17]
I'd like to have a way to "compress" thousands of geohashes that make up an entire region. By compressing the geohashes, this reduces the amount of geohashes we have to work with. See this project for more information:

https://github.com/ashwin711/georaptor

Can this be implemented as part of this project?

**Comment by mmcloughlin** [comment]
Would @Willyham's `hashfill` work for you? https://github.com/Willyham/hashfill

To your question, I think this kind of functionality belongs in another package. I'd like to keep this one simple.
