### ISSUE TITLE
Incorrect latitude encoding/decoding

### ISSUE THREAD

**Issue by lavalamp-bird** [mmcloughlin/geohash#18]
It looks as though the encoding and decoding of latitude values for the uint64 representation of geohashes has a bug:

```
func main() {

    l1, l2 := geohash.DecodeInt(geohash.EncodeInt(-118.23193457941943, 34.04134174643615))
    fmt.Printf("HERE: %v, %v\n", l1, l2)

}
```

Results in the following being printed out:

```
HERE: 33.53613084, 34.04134172
```

**Comment by mmcloughlin** [comment]
This is probably related to the fact that -118.23 is outside of the range of valid latitudes. It should be between -90 to +90. `EncodeInt` will not `panic` when you do this, but the result is meaningless.

**Comment by mmcloughlin** [comment]
Please reopen if my previous comment doesn't resolve this.

**Comment by lavalamp-bird** [comment]
Yep - problem was PEBKAC 🤣 

Sorry!
