### ISSUE TITLE
Add validation function(s) as there are no errors to check

### ISSUE THREAD

**Issue by phrozen** [mmcloughlin/geohash#19]
This is a great and complete geohash library, but there is no way to check for any kind of encoding error anywhere, it just assumes the data is valid from the start.

It would be great to add a `func Valid(string) bool` to validate that the given string is in fact a valid (modified base32) hash ready for decoding. I don't know if that is also possible for checking valid `uint64` values in precision range (60 bits?), but if it is, an extra `ValidInt(uint64) bool` function would not hurt either.

**Comment by mmcloughlin** [comment]
Thanks for filing the issue. Yes I think this would be a good addition to the API. I'm wondering if it should return an `error` instead?

```go
func Validate(string) error
```

This way we can distinguish between different failure modes; for example "too long" vs "invalid character". Thoughts?

**Comment by phrozen** [comment]
I used to return an error in my own implementation but finally figured after testing, the only real error you could have is "invalid character". Geohashes don't have a maximum precision in the original specification, and you can safely "trim" precision to 12 (60 bits) when transforming to uint64, precision over 12 is negligible because of diminishing returns. Also checking length of a string is something anyone without prior knowledge of the algorithm can do, that's why I ended just returning a bool. (Also that way I can translate and give my own error in my app).

**Comment by mmcloughlin** [comment]
Thank you for your thoughts on this. I think I prefer to return an `error` since this offers more context for anyone that cares. I'd rather not expose the more granular `ValidEncoding` and `ValidLength` since I'd rather keep my options open about how `Validate` actually works.

If you have time, I'd appreciate your thoughts on #20.

**Comment by phrozen** [comment]
Looks good enough for me. Thanks a lot for this!
