### ISSUE TITLE
Difficulty with conversion between Int to String

### ISSUE THREAD

**Issue by evanoberholster** [mmcloughlin/geohash#25]
Greetings: I am trying to convert a GeoHash uint64 to a string, but it gives me a different GeoHash than when I directly convert from Lat,Lng to String. Would you please be willing to advise as to where my error is.

The conversion between Int to String seems off for some reason.

```go
package main

import (
	"fmt"

	"github.com/mmcloughlin/geohash"
)

func main() {
	var ghS string
	var ghI uint64

	//GroundTruth dn781rjpx9gv
	lat := 35.196
	lng := -85.016
	ghS = geohash.Encode(lat, lng)
	// String dn781rjpx9gv
	fmt.Printf("%s\n", ghS)
	// Int
	fmt.Println(geohash.ConvertStringToInt(ghS))

	ghI = geohash.EncodeInt(lat, lng)
	// String b3n0vsuynrxp
	fmt.Println(geohash.ConvertIntToString(ghI, 12))
	// Int
	fmt.Printf("%d\n", ghI)
}

```

**Comment by mmcloughlin** [comment]
Ah, this is subtle. This comes down to a matter of precision.

* `Encode` gives you a 12 character geohash, where each character encodes 5 bits, so it corresponds to a 60-bit integer geohash
* `EncodeInt` gives you a full 64-bit integer geohash

The error in the above code is that `geohash.ConvertIntToString(ghI, 12)` treats `ghI` as if it is a 60-bit geohash whereas it is in fact a 64-bit geohash.

Changing this to `geohash.ConvertIntToString(ghI>>4, 12)` will give you what you expect.

**Comment by mmcloughlin** [comment]
I think this answers your question so I'm going to close the issue. Feel free to reopen if you have any more questions.
