### ISSUE TITLE
Testing BoundingBoxIntWithPrecision

### ISSUE THREAD

**Issue by missinglink** [mmcloughlin/geohash#28]
Heya,

I was using `BoundingBoxIntWithPrecision()` and noticed it returns unusual results for any precision != 64.

The test below shows that encoding a point at precision 64 and then calling `BoundingBoxIntWithPrecision` with a different precision results in bounding boxes that do not contain the original point.

I commented out a line which instead encodes the hash with the same precision used to call `BoundingBoxIntWithPrecision`, this works as expected.

I was hoping to encode my points with 64 bit precision and then use this function to discover the area covered after truncating the hash to 32 bits.

Would you consider accepting a PR for this or is this the intended behaviour?

```go
func TestBoxDecodeIntWithPrecisionShouldContain(t *testing.T) {
	cases := []struct {
		lat, lng  float64
		precision uint
	}{
		{0.0, 0.0, 64},
		{89.9, 179.9, 64},
		{0.0, 0.0, 63},
		{89.9, 179.9, 63},
		{0.0, 0.0, 32},
		{89.9, 179.9, 32},
		{0.0, 0.0, 31},
		{89.9, 179.9, 31},
	}
	for _, c := range cases {
		inthash := EncodeInt(c.lat, c.lng)
		// inthash := EncodeIntWithPrecision(c.lat, c.lng, c.precision)
		box := BoundingBoxIntWithPrecision(inthash, c.precision)
		if !box.Contains(c.lat, c.lng) {
			t.Errorf("box does not contain %f,%f", c.lat, c.lng)
		}
	}
}
```

```
--- FAIL: TestBoxDecodeIntWithPrecisionShouldContain (0.00s)
    geohash_test.go:122: box does not contain 0.000000,0.000000
    geohash_test.go:122: box does not contain 89.900000,179.900000
    geohash_test.go:122: box does not contain 0.000000,0.000000
    geohash_test.go:122: box does not contain 89.900000,179.900000
    geohash_test.go:122: box does not contain 0.000000,0.000000
    geohash_test.go:122: box does not contain 89.900000,179.900000
FAIL
FAIL	github.com/mmcloughlin/geohash	0.085s
FAIL
```

**Comment by mmcloughlin** [comment]
@missinglink I think this is working as intended. You cannot treat a full-precision integer geohash as a lower precision geohash and expect it to work.

Note that an `n`-bit geohash contains encoded data in the low `n` bits of the `uint64`. Therefore your `inthash` has encoded data in _all_ 64 bits, then when you use `BoundingBoxIntWithPrecision` this function only considers the low `c.precision` bits of `inthash`, which will actually represent some other location.

For this to work you need to translate `inthash` into a lower precision geohash by shifting right. I have not tested this but I would expect it to work.

```go
		inthash := EncodeInt(c.lat, c.lng)
		lower := inthash >> (64 - c.precision) // lower to c.precision
		box := BoundingBoxIntWithPrecision(lower, c.precision)
		if !box.Contains(c.lat, c.lng) {
			t.Errorf("box does not contain %f,%f", c.lat, c.lng)
		}
```

**Comment by missinglink** [comment]
Yeah, it seems that knowing the precision for which the `inthash` was originally encoded is strictly required.

I think there is some similarity with the other open issue https://github.com/mmcloughlin/geohash/issues/21 where we both expected that the *same point geohashed at different precisions* would share a common bit prefix, but this isn't the case.

What I was expecting was that the least signifiant bits were shifted off *and then shifted back into position*. ie:

```diff
diff --git a/geohash.go b/geohash.go
index 314fd4b..b6450b8 100644
--- a/geohash.go
+++ b/geohash.go
@@ -54,7 +54,7 @@ func encodeInt(lat, lng float64) uint64 {
 // specified number of bits.
 func EncodeIntWithPrecision(lat, lng float64, bits uint) uint64 {
        hash := EncodeInt(lat, lng)
-       return hash >> (64 - bits)
+       return (hash >> (64 - bits)) << (64 - bits)
 }
```

So what's happening is that the `inthash` bits encode like this: 

```
 1 0000000000000000000000000000000000000000000000000000000000000001
 2 0000000000000000000000000000000000000000000000000000000000000011
 3 0000000000000000000000000000000000000000000000000000000000000110
 4 0000000000000000000000000000000000000000000000000000000000001100
 5 0000000000000000000000000000000000000000000000000000000000011000
 6 0000000000000000000000000000000000000000000000000000000000110000
 7 0000000000000000000000000000000000000000000000000000000001100000
 8 0000000000000000000000000000000000000000000000000000000011000000
 9 0000000000000000000000000000000000000000000000000000000110000000
10 0000000000000000000000000000000000000000000000000000001100000000
11 0000000000000000000000000000000000000000000000000000011000000000
12 0000000000000000000000000000000000000000000000000000110000000000
13 0000000000000000000000000000000000000000000000000001100000000000
14 0000000000000000000000000000000000000000000000000011000000000000
15 0000000000000000000000000000000000000000000000000110000000000000
16 0000000000000000000000000000000000000000000000001100000000000001
17 0000000000000000000000000000000000000000000000011000000000000011
18 0000000000000000000000000000000000000000000000110000000000000110
19 0000000000000000000000000000000000000000000001100000000000001100
20 0000000000000000000000000000000000000000000011000000000000011001
21 0000000000000000000000000000000000000000000110000000000000110011
22 0000000000000000000000000000000000000000001100000000000001100111
23 0000000000000000000000000000000000000000011000000000000011001111
24 0000000000000000000000000000000000000000110000000000000110011110
25 0000000000000000000000000000000000000001100000000000001100111100
26 0000000000000000000000000000000000000011000000000000011001111001
27 0000000000000000000000000000000000000110000000000000110011110011
28 0000000000000000000000000000000000001100000000000001100111100111
29 0000000000000000000000000000000000011000000000000011001111001111
30 0000000000000000000000000000000000110000000000000110011110011110
31 0000000000000000000000000000000001100000000000001100111100111100
32 0000000000000000000000000000000011000000000000011001111001111000
33 0000000000000000000000000000000110000000000000110011110011110000
34 0000000000000000000000000000001100000000000001100111100111100000
35 0000000000000000000000000000011000000000000011001111001111000000
36 0000000000000000000000000000110000000000000110011110011110000000
37 0000000000000000000000000001100000000000001100111100111100000000
38 0000000000000000000000000011000000000000011001111001111000000000
39 0000000000000000000000000110000000000000110011110011110000000000
40 0000000000000000000000001100000000000001100111100111100000000001
41 0000000000000000000000011000000000000011001111001111000000000011
42 0000000000000000000000110000000000000110011110011110000000000110
43 0000000000000000000001100000000000001100111100111100000000001100
44 0000000000000000000011000000000000011001111001111000000000011001
45 0000000000000000000110000000000000110011110011110000000000110011
46 0000000000000000001100000000000001100111100111100000000001100111
47 0000000000000000011000000000000011001111001111000000000011001111
48 0000000000000000110000000000000110011110011110000000000110011110
49 0000000000000001100000000000001100111100111100000000001100111100
50 0000000000000011000000000000011001111001111000000000011001111001
51 0000000000000110000000000000110011110011110000000000110011110011
52 0000000000001100000000000001100111100111100000000001100111100111
53 0000000000011000000000000011001111001111000000000011001111001111
54 0000000000110000000000000110011110011110000000000110011110011110
55 0000000001100000000000001100111100111100000000001100111100111100
56 0000000011000000000000011001111001111000000000011001111001111000
57 0000000110000000000000110011110011110000000000110011110011110000
58 0000001100000000000001100111100111100000000001100111100111100000
59 0000011000000000000011001111001111000000000011001111001111000000
60 0000110000000000000110011110011110000000000110011110011110000000
61 0001100000000000001100111100111100000000001100111100111100000000
62 0011000000000000011001111001111000000000011001111001111000000000
63 0110000000000000110011110011110000000000110011110011110000000000
64 1100000000000001100111100111100000000001100111100111100000000001
```

... when I was expecting them to encode like this:

```
 1 1000000000000000000000000000000000000000000000000000000000000000
 2 1100000000000000000000000000000000000000000000000000000000000000
 3 1100000000000000000000000000000000000000000000000000000000000000
 4 1100000000000000000000000000000000000000000000000000000000000000
 5 1100000000000000000000000000000000000000000000000000000000000000
 6 1100000000000000000000000000000000000000000000000000000000000000
 7 1100000000000000000000000000000000000000000000000000000000000000
 8 1100000000000000000000000000000000000000000000000000000000000000
 9 1100000000000000000000000000000000000000000000000000000000000000
10 1100000000000000000000000000000000000000000000000000000000000000
11 1100000000000000000000000000000000000000000000000000000000000000
12 1100000000000000000000000000000000000000000000000000000000000000
13 1100000000000000000000000000000000000000000000000000000000000000
14 1100000000000000000000000000000000000000000000000000000000000000
15 1100000000000000000000000000000000000000000000000000000000000000
16 1100000000000001000000000000000000000000000000000000000000000000
17 1100000000000001100000000000000000000000000000000000000000000000
18 1100000000000001100000000000000000000000000000000000000000000000
19 1100000000000001100000000000000000000000000000000000000000000000
20 1100000000000001100100000000000000000000000000000000000000000000
21 1100000000000001100110000000000000000000000000000000000000000000
22 1100000000000001100111000000000000000000000000000000000000000000
23 1100000000000001100111100000000000000000000000000000000000000000
24 1100000000000001100111100000000000000000000000000000000000000000
25 1100000000000001100111100000000000000000000000000000000000000000
26 1100000000000001100111100100000000000000000000000000000000000000
27 1100000000000001100111100110000000000000000000000000000000000000
28 1100000000000001100111100111000000000000000000000000000000000000
29 1100000000000001100111100111100000000000000000000000000000000000
30 1100000000000001100111100111100000000000000000000000000000000000
31 1100000000000001100111100111100000000000000000000000000000000000
32 1100000000000001100111100111100000000000000000000000000000000000
33 1100000000000001100111100111100000000000000000000000000000000000
34 1100000000000001100111100111100000000000000000000000000000000000
35 1100000000000001100111100111100000000000000000000000000000000000
36 1100000000000001100111100111100000000000000000000000000000000000
37 1100000000000001100111100111100000000000000000000000000000000000
38 1100000000000001100111100111100000000000000000000000000000000000
39 1100000000000001100111100111100000000000000000000000000000000000
40 1100000000000001100111100111100000000001000000000000000000000000
41 1100000000000001100111100111100000000001100000000000000000000000
42 1100000000000001100111100111100000000001100000000000000000000000
43 1100000000000001100111100111100000000001100000000000000000000000
44 1100000000000001100111100111100000000001100100000000000000000000
45 1100000000000001100111100111100000000001100110000000000000000000
46 1100000000000001100111100111100000000001100111000000000000000000
47 1100000000000001100111100111100000000001100111100000000000000000
48 1100000000000001100111100111100000000001100111100000000000000000
49 1100000000000001100111100111100000000001100111100000000000000000
50 1100000000000001100111100111100000000001100111100100000000000000
51 1100000000000001100111100111100000000001100111100110000000000000
52 1100000000000001100111100111100000000001100111100111000000000000
53 1100000000000001100111100111100000000001100111100111100000000000
54 1100000000000001100111100111100000000001100111100111100000000000
55 1100000000000001100111100111100000000001100111100111100000000000
56 1100000000000001100111100111100000000001100111100111100000000000
57 1100000000000001100111100111100000000001100111100111100000000000
58 1100000000000001100111100111100000000001100111100111100000000000
59 1100000000000001100111100111100000000001100111100111100000000000
60 1100000000000001100111100111100000000001100111100111100000000000
61 1100000000000001100111100111100000000001100111100111100000000000
62 1100000000000001100111100111100000000001100111100111100000000000
63 1100000000000001100111100111100000000001100111100111100000000000
64 1100000000000001100111100111100000000001100111100111100000000001
```

On reflection this is somewhat of a moot point as, given an `inthash` encoded to 32 using my method, we are still not able to distinguish the original encoding precision and would get a misleading result when decoding that 32 `inthash` as a 64 🤷

**Comment by mmcloughlin** [comment]
Yes this confusion has come up multiple times before unfortunately.

Note that I did not invent integer geohashes, so I don't have the option to change how this is done, in order to maintain compatibility with existing libraries/standards. Also I think the current behavior is typically what you would want, since people using the integer versions are probably doing it for speed or compression. For example, you might reasonably want the option to store a 32-bit geohash in a `uint32`, rather than having to use a `uint64` half filled with zeros.

What do you think I could do to make this clearer? Documentation? Would it help to have a `ReduceIntPrecision` function for clarity, even though that can just be done with a `>>` operation?

**Comment by missinglink** [comment]
Gotcha,  I was assuming that this was an encoding you came up with yourself.

IMO the greatest source of confusion here is that spatial hashes are expected to share a common prefix for nearby coordinates and that you can remove chars/bits from the right to reduce the accuracy while still referencing the same general area of the globe.

I incorrectly assuming that this applied to the int version the same way it applied to the string version, can't speak for others but I think that's the trap people are falling into.

Compounding this is that the `inthash` implemention *could* actually have these properties, so developers who are more familiar with bit twiddling are falling into that trap.

I don't think it's safe to assume that developers are doing it for speed or compression, I was planning to convert the int bits to a tree structure to build a spatial index, likewise the other developer was hoping that the bytes would share a common prefix in their sorted KV store.

How to communicate all this? I guess something in the docs about `inthash` not being a spatial prefix hash would suffice.

I can write a draft of that tomorrow and open a PR where we can discuss the wording of it if you like?

Hah, sorry for the rant 🤣

**Comment by mmcloughlin** [comment]
> Gotcha, I was assuming that this was an encoding you came up with yourself.

This library is just a reimplementation of the existing "standard". The integer version was first introduced here I think

https://github.com/yinqiwen/geohash-int

I may have implemented the computation differently from others, but there may have been prior art for that too, and it's not especially novel.

https://mmcloughlin.com/posts/geohash-assembly
https://www.youtube.com/watch?v=KrsydfpDoeg

> IMO the greatest source of confusion here is that spatial hashes are expected to share a common prefix for nearby coordinates and that you can remove chars/bits from the right to reduce the accuracy while still referencing the same general area of the globe.
> 
> I incorrectly assuming that this applied to the int version the same way it applied to the string version, can't speak for others but I think that's the trap people are falling into.
> 
> Compounding this is that the `inthash` implemention _could_ actually have these properties, so developers who are more familiar with bit twiddling are falling into that trap.

The string version is literally just an encoding of the integer version in `base32`. They both have a prefix property. For integer hashes, this means that if `x = geohash_int(lat, lng, n)` then if we take a lower precision hash of the same point `y = geohash_int(lat, lng, m)` where `m < n` then `y` will be the same as the high `m` bits of `x`.

> I don't think it's safe to assume that developers are doing it for speed or compression, I was planning to convert the int bits to a tree structure to build a spatial index, likewise the other developer was hoping that the bytes would share a common prefix in their sorted KV store.
> 
> How to communicate all this? I guess something in the docs about `inthash` not being a spatial prefix hash would suffice.

I believe you can use this as a spatial prefix hash.

I'm getting a bit confused here. The difference between what this library gives you and what you seem to want is just a bitwise shift or and. If you want the behavior that a lower precision hash just has zeros in the low bits, then I suggest you just use the full precision `EncodeInt` function and use bitwise `&` to mask out the low bits.

> I can write a draft of that tomorrow and open a PR where we can discuss the wording of it if you like?
> 
> Hah, sorry for the rant 🤣

Doesn't come across as a rant 😉

**Comment by missinglink** [comment]
> The string version is literally just an encoding of the integer version in base32. They both have a prefix property. For integer hashes, this means that if x = geohash_int(lat, lng, n) then if we take a lower precision hash of the same point y = geohash_int(lat, lng, m) where m < n then y will be the same as the high m bits of x.

I unit tested this and it failed... but I realised that it's because we're interpreting your words differently 😆 
The confusion lies in the last sentence, "will be the same as the high m bits of x".

I read it as "the **high** m bits of y will be the same as the **high** m bits of x" when you meant "the **low** m bits of y will be the same as the **high** m bits of x", I don't see why these bits should be considered less significant than before?

I'm going to have a think about this a bit more but I think there are several advantages of the 'shift back again' approach over the 'just shift right', mainly in interoperability between precisions.

Right now it's possible for two disparate coordinates to hash to the same value at different precisions, eg:

```go
EncodeIntWithPrecision(-89.99884032, -179.99884036, 64) == 511181215
EncodeIntWithPrecision(-13.99897003, -103.99948501, 32) == 511181215
```

This isn't what I was expecting from a geohash, I was expecting that only very spatially nearby coordinates would share the same hash, or a common prefix.

It shows that disparate precisions are not interoperable with each other, unless, as you mentioned, you shift the bits back to the left the appropriate amount, this additional step *shouldn't* really be required IMO.

If the bits remain left aligned then different precisions are directly comparable without requiring any bit shifting.

The cool thing about this is that you can send me two precision=42 encoded `inthash` values crammed into 6 bytes each and I can determine if the two hashes intersect each other *without knowing the precision you used to encode them*.

With the current implementation you'd have to also send me one or two more bytes containing the precision you used to encode them before I could compare them.

Anyhoo... interesting conversation but I doubt you're interested in changing the algo now, I'm happy to write up a little more about the pros/cons of each if you're interested in hearing more 😆

**Comment by missinglink** [comment]
Oh actually that example isn't quite right, given two `inthash` at the same precision (ie. 42 in my example) then *either method* is sufficient to compare a common prefix since the bits 'line up', we just don't know which part of the world it refers to because when it's right aligned and not a multiple of 8.

If one variable was encoded as precision 41 and the other as 42, for instance, that's when there we're not able to compare them easily.

**Comment by mmcloughlin** [comment]
Without addressing your specific points, I'd like to demonstrate that this library is consistent with other integer geohash implementations that preceded it. I have no intention of changing the behavior, both to maintain compatibility with other implementations, and just because I believe the current behavior is reasonable.

## https://github.com/yinqiwen/geohash-int

Cloned the repo and made the following tweak to the test file.

```diff
diff --git a/test-geohash.c b/test-geohash.c
index cfe0cab..72e9a17 100755
--- a/test-geohash.c
+++ b/test-geohash.c
@@ -127,9 +127,10 @@ void test_3()
     lon_range.max = 180.0;
     lon_range.min = -180.0;

-    double latitude = 12.34;
-    double longitude = 56.78;
+    double latitude = -13.99897003; // 12.34;
+    double longitude = -103.99948501; // 56.78;

+    printf("encode (%f, %f)\n", latitude, longitude);
     for (int step = 1; step <= 32; step++)
     {
         geohash_encode(lat_range, lon_range, latitude, longitude, step, &hash);
@@ -143,8 +144,8 @@ void test_3()

 int main()
 {
-    test_1();
-    test_2();
+    // test_1();
+    // test_2();
     test_3();
     return 0;
 }
```

Now:
```
$ make test
gcc -Wall -Wextra test-geohash.c geohash.o -o geohash_test
./geohash_test
encode (-13.998970, -103.999485)
normal encode (1): 0
fast encode   (1): 0

normal encode (2): 1
fast encode   (2): 1

normal encode (3): 7
fast encode   (3): 7

normal encode (4): 30
fast encode   (4): 30

normal encode (5): 121
fast encode   (5): 121

normal encode (6): 487
fast encode   (6): 487

normal encode (7): 1950
fast encode   (7): 1950

normal encode (8): 7800
fast encode   (8): 7800

normal encode (9): 31200
fast encode   (9): 31200

normal encode (10): 124800
fast encode   (10): 124800

normal encode (11): 499200
fast encode   (11): 499200

normal encode (12): 1996801
fast encode   (12): 1996801

normal encode (13): 7987206
fast encode   (13): 7987206

normal encode (14): 31948825
fast encode   (14): 31948825

normal encode (15): 127795303
fast encode   (15): 127795303

normal encode (16): 511181215
fast encode   (16): 511181215

normal encode (17): 2044724860
fast encode   (17): 2044724860

normal encode (18): 8178899442
fast encode   (18): 8178899442

normal encode (19): 32715597771
fast encode   (19): 32715597771

normal encode (20): 130862391086
fast encode   (20): 130862391086

normal encode (21): 523449564346
fast encode   (21): 523449564346

normal encode (22): 2093798257384
fast encode   (22): 2093798257384

normal encode (23): 8375193029536
fast encode   (23): 8375193029536

normal encode (24): 33500772118145
fast encode   (24): 33500772118145

normal encode (25): 134003088472582
fast encode   (25): 134003088472582

normal encode (26): 536012353890329
fast encode   (26): 536012353890329

normal encode (27): 2144049415561319
fast encode   (27): 2144049415561319

normal encode (28): 8576197662245278
fast encode   (28): 8576197662245278

normal encode (29): 34304790648981113
fast encode   (29): 34304790648981113

normal encode (30): 137219162595924455
fast encode   (30): 137219162595924455

normal encode (31): 548876650383697822
fast encode   (31): 548876650383697822

normal encode (32): 2195506601534791288
fast encode   (32): 2195506601534791288

```

Note that in their terminology, each "step" corresponds to 2 bits of precision. At step 16 we see 511181215, agreeing with this library.

## https://github.com/sunng87/node-geohash

```
$ cat test.js
var geohash = require('ngeohash');

console.log(geohash.encode_int(-13.99897003, -103.99948501, 32));

$ node ./test.js
511181215
```

**Comment by mmcloughlin** [comment]
This does what you want:

```go
func EncodeIntWithPrecisionAlt(lat, lng float64, bits uint) {
	hash := EncodeInt(lat, lng)
	mask := ~uint64(0) << (64-bits)
	return hash & mask
}
```

**Comment by mmcloughlin** [comment]
Feel free to reopen if you have more questions, but as explained above I don't intend to change how integer geohashes are computed.

**Comment by missinglink** [comment]
Yeah fair enough.
I think I'll write a blog post about it 😃 

I went on to look at how the s2 library handles 64 bit cellIDs.
As the first step they project the sphere onto the inside of a cube, so the first division is by 6 (3 bit).

After that it's quads all the way down, leaving one extra bit which they use to indicate the level, so the rightmost 1 indicates which level a hash belongs to.

It's an interesting scheme because it prevents the hash collisions found in geohashint.

Cheers

**Comment by mmcloughlin** [comment]
I think one of the key points here is that you absolutely have to know what precision an integer geohash has been encoded at in order to use it correctly. You could store it alongside the integer geohash in your application, or you might just know it from context, but you can never just infer it from the hash value itself.

Clearly S2 solves this problem by storing it in the hash format, which makes some sense. I didn't design integer geohashes, but I understand why it was done the way it was. It's simply the non-encoded form of the string geohash. Problem is the string form _implicitly_ stores precision since it's just the length of the string itself, whereas that's lost in the non-encoded integer form.

Let me know if you do write that blog post :)
