### ISSUE TITLE
ARM / Apple M1 chips produce different results + inconsistent encoding/decoding

### ISSUE THREAD

**Issue by jackpeeples** [mmcloughlin/geohash#30]
Hello! 
I just joined a team that is using this library and my computer is using an ARM chip, while my colleagues' computers are MacBooks with intel chips. We are running the same library yet get different geohashes when encoding a lat/lng. 
Using the lat/lng pair (100,50), these are my results:
gh := geohash.encode(100,50)
on my machine: j1g8cu2yhrn5
on my colleagues' machines: j0gs3y0zh7w1

Additionally, while testing this, we noticed another problem: encoding a lat/lng then decoding the resulting hash produces a different lat/lng pair than the original input. 
on my machine:
gh := geohash.encode(100,50) (gh == j1g8cu2yhrn5)
lat, lng := geohash.decode(gh) ( (lat,lng) == (-80,49.9999998) )

on my colleagues' machine  
gh := geohash.encode(100,50) (gh == j0gs3y0zh7w1)
lat, lng := geohash.decode(gh) ( (lat,lng) == (-85,49.9999998) )

**Comment by mmcloughlin** [comment]
Does this happen for a valid lat/lng pair? 100 is out of the `[-90, 90]` range for latitude.

It's quite possible that the amd64 assembly and the pure Go versions differ for invalid points. If they differ on valid points that would be a serious problem.

Thanks for reporting the issue.

**Comment by jackpeeples** [comment]
They seem to only differ on invalid points, so that is definitely the good news. We are operating properly now with all our testing just using valid lats. I will close the issue since invalid lats are not necessarily vital. Thanks for the response!
