### ISSUE TITLE
BoundingBoxIntWithPrecision() seems inaccurate

### ISSUE THREAD

**Issue by gronka** [mmcloughlin/geohash#6]
This code
```
midGeoh = geohash.EncodeInt(35.89852207990552, -79.00791331529615)
midBox = geohash.BoundingBoxIntWithPrecision(midGeoh, 20)
fmt.Println(midBox)
fmt.Println(midBox.Center())
```

prints the following
```
{-55.37109375 -55.1953125 -146.953125 -146.6015625}
-55.283203125 -146.77734375
```

It seems as though the original point is not contained within the BoundingBox. Also, points near this point seem to return radically different results.
Perhaps I'm misunderstanding something?

**Comment by mmcloughlin** [comment]
I believe the issue is that `EncodeInt` returns a 64-bit integer geohash and you're interpreting with 20 bits of precision when you call `BoundingBoxIntWithPrecision`.

For correct results pair the `WithPrecision` functions with each other. Alternatively leave out the `WithPrecision` part and it will default to 64 bits. These options are shown below.

```go
package main

import (
	"fmt"

	"github.com/mmcloughlin/geohash"
)

var lat, lng = 35.89852207990552, -79.00791331529615

func broken() {
	midGeoh := geohash.EncodeInt(lat, lng)
	midBox := geohash.BoundingBoxIntWithPrecision(midGeoh, 20)
	fmt.Println(midBox)
	fmt.Println(midBox.Center())
	fmt.Println(midBox.Contains(lat, lng))
}

func correct() {
	midGeoh := geohash.EncodeIntWithPrecision(lat, lng, 20)
	midBox := geohash.BoundingBoxIntWithPrecision(midGeoh, 20)
	fmt.Println(midBox)
	fmt.Println(midBox.Center())
	fmt.Println(midBox.Contains(lat, lng))
}

func correct2() {
	midGeoh := geohash.EncodeInt(lat, lng)
	midBox := geohash.BoundingBoxInt(midGeoh)
	fmt.Println(midBox)
	fmt.Println(midBox.Center())
	fmt.Println(midBox.Contains(lat, lng))
}

func main() {
	broken()
	correct()
	correct2()
}
```

**Comment by gronka** [comment]
That was it! Thanks!

I'm pretty sure I figured this out when I first tried your package a month or so ago. A note in the readme could be nice - maybe at the top of the Usage section.

**Comment by mmcloughlin** [comment]
Happy to help. I think you're right, the readme could benefit from a few usage examples rather than dumping the godoc.
